# Generated by Django 6.0.3 on 2026-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('input_format', models.TextField(blank=True, verbose_name='Формат ввода')),
                ('output_format', models.TextField(blank=True, verbose_name='Формат вывода')),
                ('examples', models.JSONField(default=list, verbose_name='Примеры')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Легкая'), (2, 'Средняя'), (3, 'Сложная')], default=2, verbose_name='Сложность')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
